---
language: python
python: "2.7"
services:
  - docker
env:
  - ANSIBLE_VERSION='ansible<2'
  - ANSIBLE_VERSION='ansible>2'

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -o Dpkg::Options::="--force-confnew"  docker-engine
    
install:  
  # Install Ansible.
  - sudo pip install $ANSIBLE_VERSION
  - sudo ansible --version
  - sudo rm /usr/bin/python && sudo ln -s /usr/bin/python2.7 /usr/bin/python
  - sudo ansible-galaxy install -r tests/requirements.yml -p tests/roles/

script:  
  - ansible-playbook -i hosts --syntax-check tests/travis.yml
#  - ansible-playbook -i hosts --sudo tests/travis.yml -v
  - ansible-playbook -i hosts --sudo tests/travis.yml 
  
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email: false